package PortaoIDL;

/**
* PortaoIDL/PortaoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Portao.idl
* Quarta-feira, 17 de Outubro de 2018 10h42min32s GFT
*/

public final class PortaoHolder implements org.omg.CORBA.portable.Streamable
{
  public PortaoIDL.Portao value = null;

  public PortaoHolder ()
  {
  }

  public PortaoHolder (PortaoIDL.Portao initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PortaoIDL.PortaoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PortaoIDL.PortaoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PortaoIDL.PortaoHelper.type ();
  }

}
