package PortaoIDL;


/**
* PortaoIDL/Portao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Portao.idl
* Quarta-feira, 17 de Outubro de 2018 10h42min32s GFT
*/

public interface Portao extends PortaoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Portao
