package PortaoIDL;


/**
* PortaoIDL/PortaoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Portao.idl
* Quarta-feira, 17 de Outubro de 2018 10h42min32s GFT
*/

public abstract class PortaoPOA extends org.omg.PortableServer.Servant
 implements PortaoIDL.PortaoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("entrarVisitante", new java.lang.Integer (0));
    _methods.put ("sairVisitante", new java.lang.Integer (1));
    _methods.put ("amanhecer", new java.lang.Integer (2));
    _methods.put ("anoitecer", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PortaoIDL/Portao/entrarVisitante
       {
         this.entrarVisitante ();
         out = $rh.createReply();
         break;
       }

       case 1:  // PortaoIDL/Portao/sairVisitante
       {
         this.sairVisitante ();
         out = $rh.createReply();
         break;
       }

       case 2:  // PortaoIDL/Portao/amanhecer
       {
         this.amanhecer ();
         out = $rh.createReply();
         break;
       }

       case 3:  // PortaoIDL/Portao/anoitecer
       {
         this.anoitecer ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PortaoIDL/Portao:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Portao _this() 
  {
    return PortaoHelper.narrow(
    super._this_object());
  }

  public Portao _this(org.omg.CORBA.ORB orb) 
  {
    return PortaoHelper.narrow(
    super._this_object(orb));
  }


} // class PortaoPOA
