package PortaoIDL;


/**
* PortaoIDL/PortaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Portao.idl
* Quarta-feira, 17 de Outubro de 2018 10h42min32s GFT
*/

public interface PortaoOperations 
{
  void entrarVisitante ();
  void sairVisitante ();
  void amanhecer ();
  void anoitecer ();
} // interface PortaoOperations
