package PortaoIDL;


/**
* PortaoIDL/PortaoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Portao.idl
* Quarta-feira, 17 de Outubro de 2018 10h42min32s GFT
*/

abstract public class PortaoHelper
{
  private static String  _id = "IDL:PortaoIDL/Portao:1.0";

  public static void insert (org.omg.CORBA.Any a, PortaoIDL.Portao that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PortaoIDL.Portao extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PortaoIDL.PortaoHelper.id (), "Portao");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PortaoIDL.Portao read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PortaoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PortaoIDL.Portao value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PortaoIDL.Portao narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PortaoIDL.Portao)
      return (PortaoIDL.Portao)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PortaoIDL._PortaoStub stub = new PortaoIDL._PortaoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PortaoIDL.Portao unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PortaoIDL.Portao)
      return (PortaoIDL.Portao)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PortaoIDL._PortaoStub stub = new PortaoIDL._PortaoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
