package SinoIDL;


/**
* SinoIDL/SinoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sino.idl
* Quarta-feira, 17 de Outubro de 2018 10h42min23s GFT
*/

public interface SinoOperations 
{
  void tocarSino ();
  void pararSino ();
} // interface SinoOperations
