package SinoIDL;


/**
* SinoIDL/Sino.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sino.idl
* Quarta-feira, 17 de Outubro de 2018 10h42min23s GFT
*/

public interface Sino extends SinoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sino
