package SinoIDL;

/**
* SinoIDL/SinoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sino.idl
* Quarta-feira, 17 de Outubro de 2018 10h42min23s GFT
*/

public final class SinoHolder implements org.omg.CORBA.portable.Streamable
{
  public SinoIDL.Sino value = null;

  public SinoHolder ()
  {
  }

  public SinoHolder (SinoIDL.Sino initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SinoIDL.SinoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SinoIDL.SinoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SinoIDL.SinoHelper.type ();
  }

}
