package SinoIDL;


/**
* SinoIDL/SinoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sino.idl
* Quarta-feira, 17 de Outubro de 2018 10h42min23s GFT
*/

public abstract class SinoPOA extends org.omg.PortableServer.Servant
 implements SinoIDL.SinoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("tocarSino", new java.lang.Integer (0));
    _methods.put ("pararSino", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SinoIDL/Sino/tocarSino
       {
         this.tocarSino ();
         out = $rh.createReply();
         break;
       }

       case 1:  // SinoIDL/Sino/pararSino
       {
         this.pararSino ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SinoIDL/Sino:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Sino _this() 
  {
    return SinoHelper.narrow(
    super._this_object());
  }

  public Sino _this(org.omg.CORBA.ORB orb) 
  {
    return SinoHelper.narrow(
    super._this_object(orb));
  }


} // class SinoPOA
