package GuardaIDL;

/**
* GuardaIDL/GuardaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Guarda.idl
* Quarta-feira, 17 de Outubro de 2018 10h42min15s GFT
*/

public final class GuardaHolder implements org.omg.CORBA.portable.Streamable
{
  public GuardaIDL.Guarda value = null;

  public GuardaHolder ()
  {
  }

  public GuardaHolder (GuardaIDL.Guarda initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GuardaIDL.GuardaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GuardaIDL.GuardaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GuardaIDL.GuardaHelper.type ();
  }

}
