package GuardaIDL;


/**
* GuardaIDL/GuardaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Guarda.idl
* Quarta-feira, 17 de Outubro de 2018 10h42min15s GFT
*/

abstract public class GuardaHelper
{
  private static String  _id = "IDL:GuardaIDL/Guarda:1.0";

  public static void insert (org.omg.CORBA.Any a, GuardaIDL.Guarda that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GuardaIDL.Guarda extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GuardaIDL.GuardaHelper.id (), "Guarda");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GuardaIDL.Guarda read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GuardaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GuardaIDL.Guarda value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GuardaIDL.Guarda narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GuardaIDL.Guarda)
      return (GuardaIDL.Guarda)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GuardaIDL._GuardaStub stub = new GuardaIDL._GuardaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GuardaIDL.Guarda unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GuardaIDL.Guarda)
      return (GuardaIDL.Guarda)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GuardaIDL._GuardaStub stub = new GuardaIDL._GuardaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
