package GuardaIDL;


/**
* GuardaIDL/GuardaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Guarda.idl
* Quarta-feira, 17 de Outubro de 2018 10h42min15s GFT
*/

public interface GuardaOperations 
{
  void entrarVisitante ();
  void sairVisitante ();
} // interface GuardaOperations
